default: &default
  adapter: postgres
  encoding: utf8
  pool: 5
  username: root
  host: localhost

development:
  <<: *default
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: development

test:
  <<: *default
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: test

production:
  <<: *default
  database: production
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV['DATABASE_POOL'] %>
